services:
  microservicios-mysql8:
    container_name: microservicios-mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: zipkin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - data-mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - springcloud
    ### Después de subir el contenedor de mysql8 ejecutas lo siguiente para crear la db y el usuario de zipkin:
    ### sudo chmod +x /obs/zipkin-mysql/zipkin.sh
    ### sudo ./zipkin.sh

  microservicios-rabbitmq39:
    container_name: microservicios-rabbitmq39
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped
    networks:
      - springcloud

  zipkin-server:
    container_name: zipkin-server
    image: georgegxx/zipkin-server:latest
    ports:
      - "9411:9411"
    restart: unless-stopped
    networks:
      - springcloud
    depends_on:
      - microservicios-rabbitmq39
      - microservicios-mysql8
    environment:
      PORT: 9411
      RABBIT_ADDRESSES: microservicios-rabbitmq39:5672
      STORAGE_TYPE: mysql
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
      MYSQL_HOST: microservicios-mysql8
      #MYSQL_SERVER_URL: ec2-44-203-97-114.compute-1.amazonaws.com:3306

volumes:
  data-mysql:

networks:
    springcloud: